### ISSUE TITLE
Autopay in eCommerce - 500: Internal Server Error

### ISSUE THREAD

**Issue by jayo2005** [itpp-labs/website-addons#175]
Odoo 9

I Installed this addon and when you click on process checkout I get 500: Internal Server Error

Error Message:
`'sale.order.line' object has no attribute 'is_delivery'`

**Traceback**

```
Traceback (most recent call last):
  File "/opt/odoo/addons/website/models/ir_http.py", line 242, in _handle_exception
    response = super(ir_http, self)._handle_exception(exception)
  File "/opt/odoo/openerp/addons/base/ir/ir_http.py", line 158, in _handle_exception
    return request._handle_exception(exception)
  File "/opt/odoo/openerp/http.py", line 786, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "/opt/odoo/openerp/addons/base/ir/ir_http.py", line 183, in _dispatch
    result = request.dispatch()
  File "/opt/odoo/openerp/http.py", line 845, in dispatch
    r = self._call_function(**self.params)
  File "/opt/odoo/openerp/http.py", line 321, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/openerp/http.py", line 314, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/openerp/http.py", line 964, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/openerp/http.py", line 514, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/addons/website_sale/controllers/main.py", line 658, in checkout
    redirection = self.checkout_redirection(order)
  File "/opt/odoo/customaddons/website_sale_available/controllers/website_sale_available.py", line 19, in checkout_redirection
    for line in order.order_line if not line.is_delivery
AttributeError: 'sale.order.line' object has no attribute 'is_delivery'
```

**Comment by trojikman** [comment]
We no longer support modules for version 9.0
