### ISSUE TITLE
website_sale_checkout_store: pickup and pay at store results in error 500

### ISSUE THREAD

**Issue by Highcooley** [itpp-labs/website-addons#345]
When choosing pickup and pay at store, the payment page doesn't get loaded and a 500: internal server error message appears without a detailed error message but the following traceback information:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/odoo/addons/website/models/ir_http.py", line 273, in _handle_exception
    response = super(Http, cls)._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/base/ir/ir_http.py", line 169, in _handle_exception
    return request._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 768, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/base/ir/ir_http.py", line 195, in _dispatch
    result = request.dispatch()
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 827, in dispatch
    r = self._call_function(**self.params)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 333, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 326, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 935, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 506, in response_wrap
    response = f(*args, **kw)
  File "/mnt/modules/open/website-addons/website_sale_checkout_store/controllers/main.py", line 42, in payment
    order.force_quotation_send()
  File "/usr/lib/python2.7/dist-packages/odoo/addons/sale/models/sale.py", line 441, in force_quotation_send
    order.with_context(email_ctx).message_post_with_template(email_ctx.get('default_template_id'))
  File "/usr/lib/python2.7/dist-packages/odoo/addons/mass_mailing/models/mail_thread.py", line 51, in message_post_with_template
    return super(MailThread, no_massmail).message_post_with_template(template_id, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/mail/models/mail_thread.py", line 1949, in message_post_with_template
    update_values = composer.onchange_template_id(template_id, kwargs['composition_mode'], self._name, res_id)['value']
  File "/usr/lib/python2.7/dist-packages/odoo/addons/mail/wizard/mail_compose_message.py", line 364, in onchange_template_id
    values = self.generate_email_for_composer(template_id, [res_id])[res_id]
  File "/usr/lib/python2.7/dist-packages/odoo/addons/mail/wizard/mail_compose_message.py", line 501, in generate_email_for_composer
    template_values = self.env['mail.template'].with_context(tpl_partners_only=True).browse(template_id).generate_email(res_ids, fields=fields)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/mail/models/mail_template.py", line 528, in generate_email
    report_name = self.render_template(template.report_name, template.model, res_id)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/mail/models/mail_template.py", line 397, in render_template
    raise UserError(_("Failed to render template %r using values %r")% (template, variables))
UserError: (u"Fehler beim Erstellen der Vorlage <Template memory:7f0d6a6e7a10> mit den Werten {'format_amount': <function <lambda> at 0x7f0d6ba89398>, 'object': sale.order(2,), 'ctx': {'default_template_id': 9, 'mark_so_as_sent': True, 'active_model': 'sale.order', 'default_use_template': True, 'default_composition_mode': 'comment', 'default_mass_mailing_id': False, 'default_email_from': u'info@stadtwaechter.ch', 'default_res_id': 2, 'active_ids': [2], 'default_model': 'sale.order', 'custom_layout': 'sale.mail_template_data_notification_email_sale_order', 'tpl_partners_only': True, 'default_mass_mailing_name': False}, 'format_tz': <function <lambda> at 0x7f0d6ba89aa0>, 'user': res.users(1,), 'format_date': <function <lambda> at 0x7f0d6ba89c80>}", '')
```

Thiss error occurs with Odoo 10.0-20180122 community edition

**Comment by trojikman** [comment]
At the moment, we have stopped supporting the module in version 10.0 due to [this changes](https://github.com/odoo/odoo/pull/38885)
